routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\TableController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ReservationController;
use App\Http\Controllers\Frontend\CategoryController as FrontendCategoryController;
use App\Http\Controllers\Frontend\MenuController as FrontendMenuController;
use App\Http\Controllers\Frontend\ReservationController as FrontendReservationController;
use App\Http\Controllers\Frontend\WelcomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WelcomeController::class, 'index'])->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
Route::get('/categories', [FrontendCategoryController::class,'index'])->name('categories.index');
Route::get('/categories/{category}', [FrontendCategoryController::class,'show'])->name('categories.show');
Route::get('/menus', [FrontendMenuController::class,'index'])->name('menus.index');
Route::get('/reservation/step-one', [FrontendReservationController::class,'stepOne'])->name('reservations.step.one');
Route::post('/reservation/store/step-one/', [FrontendReservationController::class,'storeStepOne'])->name('reservations.store.step.one');
Route::get('/reservation/step-two', [FrontendReservationController::class,'stepTwo'])->name('reservations.step.two');
Route::post('/reservation/store/step-two/', [FrontendReservationController::class,'storeStepTwo'])->name('reservations.store.step.two');
Route::get('/thankYou',[WelcomeController::class,'thankYou'])->name('thankYou');


Route::middleware(['auth', 'admin'])->name('admin.')->prefix('admin')->group(function(){
    Route::get('/', [AdminController::class, 'index'])->name('index');
    route::resource('/categories', CategoryController::class);
    route::resource('/menus', MenuController::class);
    route::resource('/tables', TableController::class);
    route::resource('/reservations', ReservationController::class);
    
});
require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Menu;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'image', 'description'];

    public function menus()
    {
        return $this->belongsToMany(Menu::class, 'category_menu');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryStoreRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::all();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $image = $request->file('image')->store('public/categories');

        Category::create([
            'name' => $request->name,
            'image' => $image,
            'description' => $request->description,
        ]);

        return to_route('admin.categories.index')->with('success','Category created succesfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required',
            'description' => 'required'
        ]);
        $image = $category->image;
        if($request->hasFile('image')){
            Storage::delete($category->image);
            $image = $request->file('image')->store('public/categories');
        }

        $category->update([
            'name' => $request->name,
            'description' => $request->description,
            'image' => $image
        ]);

        return to_route('admin.categories.index')->with('warning','Category updated succesfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        Storage::delete($category->image);
        $category->menus()->detach();
        $category->delete();
        return to_route('admin.categories.index')->with('danger','Category destroyed succesfully');
    }
}

app/Http/Controllers/Frontend/CategoryController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index(){
        $categories=Category::all();
        return view('categories.index', compact('categories'));

    }
    public function show(Category $category){
        return view('categories.show', compact('category'));
        
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/categories/index.blade.php
<x-guest-layout>
  <div
      class="container  max-w-lg px-4 py-56 mx-auto text-left bg-center bg-no-repeat bg-cover sm:max-w-none md:text-center min-h-max"
      style="background-image: url('https://cdn.pixabay.com/photo/2016/11/18/14/39/beans-1834984_960_720.jpg')">
      <h1
        class="font-mono text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-green-400 to-blue-500 text-center sm:leading-none lg:text-5xl">
        <span class="inline md:block">Welcome To Categories</span>
      </h1>
      
      {{-- <div class="flex flex-col items-center mt-12 text-center">
        <span class="relative inline-flex w-full md:w-auto">
          <a href="{{route('reservations.step.one')}}" type="button"
            class="inline-flex items-center justify-center px-6 py-2 text-base font-bold leading-6 text-white bg-green-600 rounded-full lg:w-full md:w-auto hover:bg-green-500 focus:outline-none">
            Make your Reservation
          </a>
      </div> --}}
    </div>
    <div class="container w-full px-5 py-6 mx-auto">
      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-y-6 justify-center ">
            @foreach ($categories as $category)        
            <div class="max-w-xs mx-4 mb-2 rounded-lg shadow-lg mx-auto text-center w-72">
              <img class="w-full h-48" src="{{Storage::url($category->image)}}"
                alt="Image" />
              <div class="px-6 py-4">
                <a href="{{route('categories.show' ,$category->id)}}">
                    <h4 class="mb-3 text-xl font-semibold tracking-tight text-green-600 uppercase hover:text-green-400">{{$category->name}}</h4>

                </a>
              </div>
            </div>
            @endforeach
        </div>
      </div>
</x-guest-layout>

resources/views/categories/show.blade.php
<x-guest-layout>
    <div class="container w-full px-5 py-6 mx-auto">
        <div class="grid lg:grid-cols-4 gap-y-6">
            @foreach ($category->menus as $menu)        
            <div class="max-w-xs mx-4 mb-2 rounded-lg shadow-lg">
                <img class="w-full h-48" src="{{Storage::url($menu->image)}}"
                    alt="Image" />
                <div class="px-6 py-4">
                    <h4 class="mb-3 text-xl font-semibold tracking-tight text-green-600 uppercase hover:text-green-400">{{$menu->name}}</h4>
                    <p class="leading-normal text-gray-700">{{$menu->description
                    }}</p>
                </div>
                <div class="flex items-center justify-between p-4">
                    <button class="px-4 py-2 bg-green-600 text-green-50">Order Now</button>
                    <span class="text-xl text-green-600">{{$menu->price}}$</span>
                </div>
            </div>
            @endforeach
        </div>
      </div>
</x-guest-layout>